apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-crt
  namespace: ingress-nginx
spec:
  secretName: wildcard-tls
  dnsNames:
  - '*.2.bluddclot.com'
  issuerRef:
    name: letsencrypt-bluddclot2
    kind: ClusterIssuer
    group: cert-manager.io
