apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: k0s1.two.bluddclot.com
      user: debian
      port: 22
    role: controller
  - ssh:
      address: kworker1.two.bluddclot.com
      user: debian
      port: 22
    role: worker
  - ssh:
      address: kworker2.two.bluddclot.com
      user: debian
      port: 22
    role: worker
  k0s:
    version: 1.26.0+k0s.0
    dynamicConfig: false
