apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./metallb.yaml
- ./cert-manager.yaml
- ./ingress.yaml
- ./wildcard-cert.yaml
- ./awx-operator.yaml
- ./awx-bcas.yaml
- ./nfs-csi.yaml
- ./nfs-storageclass.yaml
- ./argo-ingress.yaml
