apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-metallb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster1/argocd/metallb
    repoURL: ssh://git@gitea.c1.slow.moda:222/jr/k8s1.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
